# Generated by Django 5.2.14 on 2026-07-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
