# Generated by Django 5.2.14 on 2026-07-21 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_deleted_at_alter_booking_check_in_and_more'),
        ('rooms', '0006_roomtype_room_room_type_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requested_room_type',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='rooms.room'),
        ),
    ]
