# Generated by Django 5.2.14 on 2026-07-21 05:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('CANCEL_BOOKING', 'Cancel Booking'), ('CREATE_BOOKING', 'Create Booking'), ('ADD_PAYMENT', 'Add Payment'), ('ADD_CHARGE', 'Add Charge'), ('TOGGLE_CLEAN', 'Toggle Clean Status'), ('TOGGLE_INSPECT', 'Toggle Inspect Status'), ('ROOM_CREATED', 'Room Created'), ('ROOM_UPDATED', 'Room Updated'), ('ROOM_DELETED', 'Room Deleted'), ('GUEST_CREATED', 'Guest Created'), ('GUEST_UPDATED', 'Guest Updated'), ('GUEST_DELETED', 'Guest Deleted'), ('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated')], db_index=True, max_length=50)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
