# Generated by Django 5.2.14 on 2026-07-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='Sunrise Hotel & Resort', max_length=100)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Room tax rate percentage', max_digits=5)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('weekend_surge_multiplier', models.DecimalField(decimal_places=2, default=1.2, help_text='Price multiplier for Fri/Sat nights', max_digits=4)),
                ('check_in_time', models.CharField(default='14:00', max_length=10)),
                ('check_out_time', models.CharField(default='11:00', max_length=10)),
                ('cancellation_grace_hours', models.IntegerField(default=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
