# Generated by Django 5.2.14 on 2026-07-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated amenities', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('DOUBLE', 'Double'), ('TWIN', 'Twin'), ('DELUXE', 'Deluxe'), ('SUITE', 'Suite'), ('FAMILY', 'Family')], default='SINGLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20),
        ),
    ]
