# Generated by Django 5.2.14 on 2026-07-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_amenities_room_description_alter_room_room_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
