# Generated by Django 5.2.14 on 2026-07-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_clean',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_inspected',
            field=models.BooleanField(default=True),
        ),
    ]
