# Generated by Django 5.2.14 on 2026-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_is_clean_room_is_inspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_clean',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_inspected',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='AVAILABLE', max_length=20),
        ),
    ]
