# Generated by Django 5.2.14 on 2026-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_guest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='guest',
            name='document_number',
            field=models.CharField(db_index=True, help_text='CNIC / Passport Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
